version: 2.1
setup: true

jobs:
  setup:
    docker:
      - image: clojure:tools-deps
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            cd projects/app && clojure -M --report stderr -m app.main > generated_config.yml
      - continuation/continue:
          configuration_path: projects/app/generated_config.yml

workflows:
  setup:
    jobs:
      - setup
