version: 2.1
setup: true


orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    docker:
      - image: clojure:tools-deps
    steps:
      - checkout
      - run: "apt-get update && apt-get install -y curl jq && rm -rf /var/lib/apt/lists/*"
      - run:
          name: Generate config
          command: |
            cd projects/app && clojure -M --report stderr -m app.main > generated_config.yml
      - continuation/continue:
          configuration_path: projects/app/generated_config.yml

workflows:
  setup:
    jobs:
      - setup
